src/courses/urls.py
from django.urls import path

from . import views, views_my
import homeworks.views as homework_views

app_name = 'courses'
urlpatterns = [
    # Basic operation
    # path('', views.PlatformHomepageView.as_view(), name='index'),
    path('create', views.CreateCourseView.as_view(), name='course_create'),
    path('<int:course_id>', views.course_homepage, name='course_homepage'),
    path('<int:pk>/edit', views.EditCourseView.as_view(), name='course_edit'),
    path('<int:course_id>/join', views.joinCourse, name='course_join'),

    # My* Views
    path('myTeaching', views_my.MyTeachingCourseListView.as_view(), name='teaching_list_my'),
    path('myStudying', views_my.MyStudyingCourseListView.as_view(), name='studying_list_my'),
    path('myTasks', views_my.MyTasksListView.as_view(), name='tasks_list_my'),

    # Member management
    path('<int:course_id>/students', views.StudentsListView.as_view(), name='students_manage'),
    path('changePrivilege/<int:member_record>', views.ChangePrivilegeView.as_view(), name='privilege_change'),

    # Task handling 
    path('<int:course_id>/tasks', homework_views.TaskListView.as_view(), name='task_list'),
    path('<int:course_id>/createTask', homework_views.CreateTaskView.as_view(), name='task_create'),
    path('task/<int:task_id>', homework_views.TaskDetailView.as_view(), name='task_detail'),
    path('task/<int:pk>/update', homework_views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:task_id>/submissions', homework_views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:pk>/comment', homework_views.SubmissionCommentUpdateView.as_view(), name='submission_comment'),

    # TODOs
    # path('<int:course_id>/announcements', views.manageAnnounce, name='manage_announces'),
]

src/dockers/urls.py
from django.urls import path

from . import views

app_name = 'dockers'
urlpatterns = [
    path('<int:task_id>/uploadDockerfile', views.UploadDockerfileView.as_view(), name='dockerfile_upload'),
    # path('image/<int:dockerfile_id>', views.DockerfileDetailView, name='dockerfile_view'),
    # path('review', views.ReviewDockerListView.as_view(), name='dockerfile_review'),
    path('<int:submission_id>/containerStatus', views.containerStatus, name='container_status'),
    # path('<int:submission_id>', views.index, name='container_list'),
    path('<int:submission_id>/createContainer', views.createContainer, name='container_create'),
    path('<int:submission_id>/deleteContainer', views.deleteContainer, name='container_delete'),
]

src/files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    # path('', views.FileCreateView.as_view(), name='index'),
    path('', views.TestUploadFileFormView.as_view(), name='index'),
    path('download/<int:file_id>', views.downloadFile, name='download'),
    path('delete/<int:file_id>', views.deleteFile, name='delete'),
]

src/homeworks/urls.py
from django.urls import path

from . import views

app_name = 'homeworks'
urlpatterns = [
    # path('<int:course_id>', views.TaskListView.as_view(), name='task_list'),
    # path('task/<int:task_id>', views.TaskDetailView.as_view(), name='task_detail'),
    # path('<int:course_id>/createTask', views.CreateTaskView.as_view(), name='task_create'),
    # path('task/<int:task_id>/submissions', views.SubmissionListView.as_view(), name='submission_list'),
    # path('submission/<int:pk>/comment', views.SubmissionCommentUpdateView.as_view(), name='submission_comment'),
]

src/trial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
import courses.views, users.views

urlpatterns = [
    path('', courses.views.PlatformHomepageView.as_view(), name='index'),
    path('login/', users.views.LoginView.as_view(), name='login'),
    # path('', index, name="home"),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('homeworks/', include('homeworks.urls')),
    path('files/', include('files.urls')),
    path('dockers/', include('dockers.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.LoginView.as_view(), name='index'),
    # path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'logout/', views.logout_func, name='logout'),
    path(r'signup/', views.SignupView.as_view(), name='signup'),
    path(r'profile/<str:username>', views.profile, name='profile'),
    path(r'profile_edit', views.EditUserInfoView.as_view(), name='edit'),
]

src/homeworks/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import User
from django.http import FileResponse

from courses.models import Course
from files.models import SubmissionFile, DockerFile

class Task(models.Model):
    TASK_STATUS = [(0, 'draft'), (1, 'running'), (2, 'closed')]

    # main info
    title = models.CharField('title', max_length=64)
    description = models.CharField('description', max_length=1024)
    tips = models.CharField('tips', max_length=1024, blank=True)
    answer = models.CharField('answer', max_length=1024, blank=True)
    have_docker = models.BooleanField("have docker experiment", default=False)
    dockerfile = models.OneToOneField(DockerFile, on_delete=models.SET_NULL, blank=True, null=True)
    auxiliary_file = models.OneToOneField(SubmissionFile, on_delete=models.SET_NULL, blank=True, null=True)

    # status info
    status = models.IntegerField(
        'homework status', choices=TASK_STATUS, default=0)
    create_date = models.DateTimeField('date created', default=timezone.now())
    close_date = models.DateTimeField(
        'date to close', default=timezone.now() + timedelta(days=30))

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="tasks", null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks_created", null=True)

    def __str__(self):
        return "Task({}):{}".format(self.pk, self.title)


class Submission(models.Model):
    SUBMISSION_STATUS = [ (0, "Unfinished"), (1, "Submitted"), (2, "Commented") ]

    status = models.IntegerField(
        'status', default=0, choices=SUBMISSION_STATUS)

    commit_date = models.DateTimeField('date committed', default=timezone.now())
    score = models.IntegerField('score', null=True)
    comment = models.CharField('comment', max_length=1024, null=True)

    # course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="submissions", null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="submissions", null=True)
    submitter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="submissions", null=True)
    file = models.OneToOneField(SubmissionFile, on_delete=models.SET_NULL, null=True, blank=True, related_name="submission")

    def get_file_response(self):
        path = self.file.get_local_path()
        response = FileResponse(open(path, "rb"), filename=self.file.name)
        print(path)
        return response

src/homeworks/forms.py
from django import forms
from .models import Task, Submission

class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ("title", "description", "tips", "close_date", "answer")

src/homeworks/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, FileResponse
from django.utils import timezone
from django.core.exceptions import PermissionDenied, ValidationError
from django.views import View
from django.views.generic import ListView, UpdateView
from django.views.generic.base import ContextMixin
from django.contrib import messages

from courses.models import Course, CourseMember
from .forms import TaskForm
from .models import Task, Submission
# HomeworkStatu is Submission now
from files.forms import UploadFileForm

import json
import datetime

from utils.general import return_error, check_authenticated_and, info
from utils.status import *
from utils.check import SetLoginRequiredMixin, CheckGreaterPrivilegeMixin
from utils.params import *
from .utils import SUBMISSION_STATUS

class TaskListView(CheckGreaterPrivilegeMixin, ListView):
    """
    List all the tasks in the same course
    """
    least_privilege = COURSEMEMBER_STUDENT
    paginate_by = 10
    template_name = 'homeworks/task_list.html'
    context_object_name = 'task_list'

    def dispatch(self, request, *args, **kwargs):
        self.course_id = kwargs["course_id"]
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        course_id = self.course_id
        return Task.objects.filter(course__pk=course_id)

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        context['course_id'] = self.course_id
        context['title'] = "Task List"
        context['is_teacher'] = (CourseMember.get_highest_course_privilege(self.request.user.pk, context['course_id']) < 2)
        return context

    # def get(self, request, course_id):
    #     res, response = check_authenticated_and(request, CourseMember.is_member_of(request.user.pk, course_id), USER_NOT_AUTHORIZED)
    #     if res == False:
    #         return response

    #     # Authorized user
    #     return super(TaskListView, self).get(self, request)
    

class CreateTaskView(SetLoginRequiredMixin, ContextMixin, View):
    template_name = "homeworks/task_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Task"
        return context
    
    def get(self, request, course_id):
        context = self.get_context_data()
        context['form'] = TaskForm()
        context['course_id'] = course_id
        context['is_teacher'] = (CourseMember.get_highest_course_privilege(request.user.pk, course_id) < 2)
        return render(request, self.template_name, context)
        
    def post(self, request, course_id):
        res, response = check_authenticated_and(request, CourseMember.is_teacher_of(request.user.pk, course_id), USER_NOT_AUTHORIZED)
        if res == False:
            return response

        # Authorized as teacher
        form = TaskForm(request.POST)
        if form.is_valid():
            # Submitted fields: title, description, tips, close_date, answer
            task = form.save()
            task.course = get_object_or_404(Course, pk=course_id)
            task.creator = request.user
            task.save()
            messages.info(request, "Create Task successfully")
            return redirect(reverse("courses:task_list", args=[course_id]))

        context = self.get_context_data()
        context['form'] = form
        context['course_id'] = course_id
        return render(request, self.template_name, {"form": form, 'course_id': course_id})

class TaskDetailView(SetLoginRequiredMixin, ContextMixin, View):
    """
    Display the detail of specific task

    Privilege: more than student
    
    For students of the task:
        * Display details of the task
        * Upload, delete the commited file
    For non-students:
        * Display details of the task
        * Redirect to submissions of the task
    """
    template_name = "homeworks/task_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Task Detail"
        return context

    def get(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        if request.user.is_authenticated and CourseMember.is_member_of(request.user.pk, task.course.pk):
            # User is member
            privilege = CourseMember.get_highest_course_privilege(request.user.pk, task.course.pk)
            context = self.get_context_data()
            context['task'] = task
            if privilege == 3:
                # One and only one
                try:
                    submission = Submission.objects.get(task__pk=task_id, submitter__pk=request.user.pk)
                    context['submission'] = submission
                except Submission.DoesNotExist:
                    # submission = None
                    submission = Submission(submitter=request.user, task=task)
                    submission.save()
                except Exception as e:
                    # More than one copy
                    print(e)
                    # messages.error("More than one copy for {} in {}".format(request.user.pk, task_id))
                    raise e
                finally:
                    context['submission'] = submission
                    try:
                        file = submission.file
                        print(file.name)
                    except:
                        context['to_submit'] = True
                        context['form'] = UploadFileForm()
            else:
                # link to submission list
                context["is_teacher"] = True
                # context['']
            return render(request, self.template_name, context=context)
        return return_error(request, USER_NOT_AUTHENTICATED)

    def post(self, request, task_id):
        context = self.get_context_data()
        task = get_object_or_404(Task, pk=task_id)

        if request.user.is_authenticated and CourseMember.is_student_of(request.user.pk, task.course.pk):
            try:
                submission = Submission.objects.get(task__pk=task_id, submitter__pk=request.user.pk)
                form = UploadFileForm(files=request.FILES)
                if form.is_valid():
                    file = form.save()
                    submission.file = file
                    submission.save()
                    messages.info(request, "Successfully submit homework")
                    return redirect(reverse("courses:task_detail", args=[task_id]))
                messages.info(request, "Fail to validate form.")
                context['form'] = form
                print(form.errors)
                return render(request, self.template_name, context=context)
            except Submission.DoesNotExist:
                # Normal case
                form = UploadFileForm(files=request.FILES)
                if form.is_valid():
                    file = form.save()
                    submission = Submission(submitter=request.user, task=task, file=file)
                    submission.save()
                    messages.info(request, "Successfully submit homework")
                    return redirect(reverse("courses:task_detail", args=[task_id]))
                messages.info(request, "Fail to validate form.")
                context['form'] = form
                print(form.errors)
                return render(request, self.template_name, context=context)
            except Exception as e:
                # More than one copy
                print(e)
                messages.error("More than one copy for {} in {}".format(request.user.pk, task_id))
                return redirect(reverse("courses:task_detail", args=[task_id]))
        return redirect(reverse("courses:task_detail", args=[task_id]))

class SubmissionListView(CheckGreaterPrivilegeMixin, ListView):
    least_privilege = COURSEMEMBER_TEACHER

    paginate_by = 10
    template_name = 'homeworks/submission_list.html'
    context_object_name = 'submission_list'

    def dispatch(self, request, *args, **kwargs):
        self.task_id = kwargs["task_id"]

        course = Task.objects.get(pk=self.task_id).course
        self.course_id = course.pk
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        return Submission.objects.filter(task__pk=self.task_id)

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        context['title'] = "Submission List"
        context['task_id'] = self.task_id
        return context

    def get(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)

        res, response = check_authenticated_and(request, CourseMember.is_teacher_of(request.user.pk, task.course.pk), USER_NOT_AUTHORIZED)
        if res == False:
            return response

        # Authorized user
        return super(SubmissionListView, self).get(self, request)

class SubmissionCommentUpdateView(CheckGreaterPrivilegeMixin, UpdateView):
    least_privilege = COURSEMEMBER_TEACHER

    model = Submission
    fields = ["status", "score", "comment"]
    success_url = "/"
    template_name = "homeworks/submission_update.html"

    def dispatch(self, request, *args, **kwargs):
        self.submission_id = kwargs["pk"]

        self.course_id = Submission.objects.get(pk=self.submission_id).task.course.pk
        print("Submission({}) with Course({})".format(self.submission_id, self.course_id))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        submission_id = self.object.pk
        # download_link = self.object.get_download_url()
        print(self.object.file)

src/templates/homeworks/submission_list.html
{% extends 'generics/base.html' %}

{% block content %}

<div class="col-8 d-flex justify-content-center mt-3">
<table class="table">

<tr>
    <th>User</th>
    <th>Status</th>
    <th>Commit Date</th>
    <th>Score</th>
    <th>Comment</th>
    <th>Option</th>
</tr>

<tr>
{% for submission in submission_list %}

    <td>
        <a href="{% url 'users:profile' submission.submitter.pk %}">{{ submission.submitter.username }}</a>
    </td>
    <td>{{ submission.status }}</td>
    <td>{{ submission.commit_date }}</td>
    <td>{{ submission.score }}</td>
    <td>{{ submission.comment }}</td>
    <td>
    {% if submission.file %}
        <a href="{% url 'courses:submission_comment' submission.pk %}">Review</a>
    {% else %}
        Not Available
    {% endif %}
    </td>

{% endfor %}
</tr>

</table>
</div>

{% endblock content %}

src/templates/homeworks/submission_update.html
{% extends "generics/base.html" %}

{% block content %}

<form action="{% url 'courses:submission_comment' submission_id %}" method="post">
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
    {% csrf_token %}
    <table class="table">
    {% for field in form %}
        <tr>
            <td>
                {{ field.label_tag }}
            </td>
            <td>
                {{ field }}
            </td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}

        <tr>
            <td>Submitted file</td>
            <td>
                <a href="{% url 'files:download' file_id %}" _target="blank">Download</a>
            </td>
        </tr>
    </table>
<input type="submit" value="Update" class="offset-3">
</form>

{% endblock content %}

src/templates/homeworks/task_create.html
{% extends 'generics/base.html' %}

{% block content %}

<form action="{% url 'courses:task_create' course_id %}" method="post">
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
{% csrf_token %}

    <table class="table table-borderless">
    {% for field in form %}
        <tr>
            <td>
                {{ field.label_tag }}
            </td>
            <td>
                {{ field }}
            </td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
    </table>
<input type="submit" value="Submit" class="offset-4">
</form>
{% endblock content %}

src/templates/homeworks/task_detail.html
{% extends 'generics/base.html' %}

{% block content %}

<h2>Information</h2>
<table class="table table-borderless">
    <tr>
        <td>Title</td>
        <td>{{ task.title }}</td>
    </tr>
    <tr>
        <td>Course</td>
        <td>{{ task.course.name }}</td>
    </tr>
    <tr>
        <td>Description</td>
        <td>{{ task.description|default:"N/A" }}</td>
    </tr>
    <tr>
        <td>Tips</td>
        <td>{{ task.tips|default:"N/A" }}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>
        {% if task.status == 0 %}
        Draft
        {% elif task.status == 1 %}
        Running
        {% else %}
        Closed
        {% endif %}
        </td>
    </tr>
    <tr>
        <td>Created Date</td>
        <td>{{ task.create_date }}</td>
    </tr>
    <tr>
        <td>Close Date</td>
        <td>{{ task.close_date}}</td>
    </tr>
    {% if task.auxiliary_file %}
    <tr>
        <td>Auxiliary File</td>
        <td>
        <a href="{% url 'files:download' task.auxiliary_file.pk %}">Download</a>
        </td>
    </tr>
    {% endif %}
</table>

{% if is_teacher %}
<div class="row mt-3">
    <div class="m-1 col-2">
        <a href="{% url 'courses:task_update' task.pk %}" class="btn btn-primary" style="width: auto">Update Task</a>
    </div>

    <div class="m-1 col-2">
        <a href="{% url 'courses:submission_list' task.pk %}" class="btn btn-primary" style="width: auto">Submission List</a>
    </div>

    <div class="m-1 col-2">
        <a href="{% url 'dockers:dockerfile_upload' task.pk %}" class="btn btn-primary" style="width: auto">Upload Experiment</a>
    </div>
</div>
{% else %}
<div class="row">
{% if to_submit %}
    {% include "homeworks/includes/upload_homeworkfile_form.html" %}
{% else %}
<h2>Uploaded file Details:</h2>
<table class="table table-borderless">
    <tr>
        <td>Filename</td>
        <td>{{ submission.file.name }}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>{{ submission.status}}</td>
    </tr>
    <tr>
        <td>Commit Date</td>
        <td>{{ submission.commit_date }}</td>
    </tr>
    <tr>
        <td>Score</td>
        <td>
        {% if submission.score %}
            {{ submission.score }}
        {% else %}
            <div style='color=red'>Not given yet.</div>
        {% endif %}
        </td>
    </tr>
    <tr>
    <td>Operations</td>
    <td>
        <a href="{% url 'files:download' submission.file.pk %}" target="_blank">Download</a>
        <a href="{% url 'files:delete' submission.file.pk %}" target="_blank">Delete</a>
    </td>
    </tr>
</table>
<p>Refresh the page after deletion.</p>
{% endif %}
{% if task.have_docker %}
    {% include "dockers/includes/container_status.html" %}
{% endif %}
</div>

{% endif %}


{% endblock content %}

src/templates/homeworks/task_list.html
{% extends 'generics/base.html' %}

{% block content %}

{% if is_teacher %}
<div class="d-flex justify-content-baseline m-3">
    <a href="{% url 'courses:task_create' course_id %}" class="btn btn-primary" style="width: auto">
        Create New Task
    </a>
</div>
{% endif %}

<div class="container mt-2">
<table class="table">
<thead>
    <tr>
    <th scope="col" hidden="True">id</th>
    <th scope="col">Task</th>
    <th scope="col">Creator</th>
    <th scope="col">Status</th>
    <th scope="col">Close Date</th>
    </tr>
</thead>

{% for task in task_list %}

<tr>
    <td hidden="True">{{ task.pk }}</td>
    <td>
        <a href="{% url 'courses:task_detail' task.pk %}">
        {{ task.title }}
        </a>
    </td>

    <td>{{ task.creator.username }}</td>
    <td>
        {% if task.status == 0 %}
            Draft
        {% elif task.status == 1 %}
            Running
        {% elif task.status == 2 %}
            Closed
        {% endif %} 
    </td>
    <td>{{ task.close_date }}</td>
</tr>
{% endfor %}
</table>
</div>

{% if page_obj %}
<nav aria-label="Page navigation example">
<ul class="pagination d-flex justify-content-center m-3">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Previous</a></li>
    {% endif %}
    {% for object in page_obj.paginator.page_range %}
        <li class="page-item">
            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Next</a></li>
    {% endif %}
</ul>
</nav>
{% endif %}

{% endblock content %}

src/templates/homeworks/task_update.html
{% extends "generics/base.html" %}

{% block content %}

<form action="{% url 'courses:task_update' task_id %}" method="post">
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
    {% csrf_token %}

    <table class="table table-borderless">
        <tr>
            <td>
                <label for="{{ form.title.id_for_label }}">
                    Title
                </label>
            </td>
            <td>
                {{ form.title }}
            </td>
            <td>{{ form.title.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.description.id_for_label }}">
                   Description 
                </label>
            </td>
            <td>
                {{ form.description }}
            </td>
            <td>{{ form.description.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.tips.id_for_label }}">
                    Tips
                </label>
            </td>
            <td>
                {{ form.tips }}
            </td>
            <td>{{ form.tips.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.answer.id_for_label }}">
                    Answer
                </label>
            </td>
            <td>
                {{ form.answer }}
            </td>
            <td>{{ form.answer.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.status.id_for_label }}">
                    Status
                </label>
            </td>
            <td>
                {{ form.status }}
            </td>
            <td>{{ form.status.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.close_date.id_for_label }}">
                    Date to close
                </label>
            </td>
            <td>
                {{ form.close_date }}
            </td>
            <td>{{ form.close_date.errors }}</td>
        </tr>
        <tr>
            <td>
                <label for="{{ form.auxiliary_file.id_for_label }}">
                    Auxiliary File
                </label>
            </td>
            <td>
                {{ form.auxiliary_file }}
            </td>
            <td>{{ form.auxiliary_file.errors }}</td>
        </tr>
    </table>

<div class="row">
<div class="d-flex justify-content-center col-3">
    <a href="{% url 'files:index' %}" class="">Upload New File</a>
</div>

<div class="col-3">
    <input type="submit" value="Update">
</div>
</div>
</form>

{% endblock content %}