src/courses/urls.py
from django.urls import path

from . import views, views_my
import homeworks.views as homework_views

app_name = 'courses'
urlpatterns = [
    # Basic operation
    # path('', views.PlatformHomepageView.as_view(), name='index'),
    path('create', views.CreateCourseView.as_view(), name='course_create'),
    path('<int:course_id>', views.course_homepage, name='course_homepage'),
    path('<int:pk>/edit', views.EditCourseView.as_view(), name='course_edit'),
    path('<int:course_id>/join', views.joinCourse, name='course_join'),

    # My* Views
    path('myTeaching', views_my.MyTeachingCourseListView.as_view(), name='teaching_list_my'),
    path('myStudying', views_my.MyStudyingCourseListView.as_view(), name='studying_list_my'),
    path('myTasks', views_my.MyTasksListView.as_view(), name='tasks_list_my'),

    # Member management
    path('<int:course_id>/students', views.StudentsListView.as_view(), name='students_manage'),
    path('changePrivilege/<int:member_record>', views.ChangePrivilegeView.as_view(), name='privilege_change'),

    # Task handling 
    path('<int:course_id>/tasks', homework_views.TaskListView.as_view(), name='task_list'),
    path('<int:course_id>/createTask', homework_views.CreateTaskView.as_view(), name='task_create'),
    path('task/<int:task_id>', homework_views.TaskDetailView.as_view(), name='task_detail'),
    path('task/<int:pk>/update', homework_views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:task_id>/submissions', homework_views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:pk>/comment', homework_views.SubmissionCommentUpdateView.as_view(), name='submission_comment'),

    # TODOs
    # path('<int:course_id>/announcements', views.manageAnnounce, name='manage_announces'),
]

src/files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    # path('', views.FileCreateView.as_view(), name='index'),
    path('', views.TestUploadFileFormView.as_view(), name='index'),
    path('download/<int:file_id>', views.downloadFile, name='download'),
    path('delete/<int:file_id>', views.deleteFile, name='delete'),
]

src/trial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
import courses.views, users.views

urlpatterns = [
    path('', courses.views.PlatformHomepageView.as_view(), name='index'),
    path('login/', users.views.LoginView.as_view(), name='login'),
    # path('', index, name="home"),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('homeworks/', include('homeworks.urls')),
    path('files/', include('files.urls')),
    path('dockers/', include('dockers.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.LoginView.as_view(), name='index'),
    # path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'logout/', views.logout_func, name='logout'),
    path(r'signup/', views.SignupView.as_view(), name='signup'),
    path(r'profile/<str:username>', views.profile, name='profile'),
    path(r'profile_edit', views.EditUserInfoView.as_view(), name='edit'),
]

src/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

import datetime

# Create your models here.


class UserAuxiliary(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="auxiliary", unique=True)

    # avatar = models.CharField('avatar path', max_length=128, blank=True)
    realname = models.CharField('real name', max_length=16, blank=True, null=True)
    uid = models.CharField('user(student/teacher) number', max_length=32, blank=True, null=True)

    def __str__(self):
        return "<User: {}".format(self.user.username)

    class Meta:
        verbose_name = verbose_name_plural = "User auxiliary information"

src/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

# from .models import UserAuxiliary

class UserForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        verbose_name = 'User'
        verbose_name_plural = 'Users'

        fields = (
            'username', 'password1', 'password2', 'email' 
        )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = self.cleaned_data

        if data['password1'] != data['password2']:
            raise ValidationError("Two password not match")

        return data

class LoginForm(forms.Form):
    # email = forms.EmailField(label='email')
    username = forms.CharField(max_length=256)
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
    
    def clean(self):
        data = self.cleaned_data
        user = authenticate(username=data['username'], password=data['password'])

        if user == None:
            raise ValidationError("No such user or wrong password")

        return data

class EditForm(forms.Form):
    realname = forms.CharField(max_length=16)
    uid = forms.CharField(max_length=32)
    email = forms.EmailField()

src/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views import View
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin

from courses.models import Course, CourseMember
from utils.check import SetLoginRequiredMixin
from .models import UserAuxiliary
from .forms import UserForm, LoginForm, EditForm
from .utils import get_enrolled_courses

class SignupView(View):
    template_name = 'users/signup.html'

    def get_context_data(self, **kwargs):
        context = {}
        context["title"] = "Sign Up"
        return context

    def get(self, request):
        user = UserForm()
        context = self.get_context_data()
        context["form"] = user
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserForm(request.POST)

        if form.is_valid():
            obj = form.save()
            obj.auxiliary = UserAuxiliary(user=obj)
            obj.auxiliary.save()
            return HttpResponseRedirect(reverse("login"))

        context = self.get_context_data()
        context["form"] = form
        return render(request, self.template_name, context)

class LoginView(View):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = {}
        context["title"] = "Login"
        return context

    def get(self, request):
        context = self.get_context_data()
        form = LoginForm()

        if request.user.is_authenticated:
            return redirect(reverse("users:profile", args=[request.user.username]))

        context["form"] = form
        context["title"] = "Login"
        request.session['referer'] = request.META.get('HTTP_REFERER', reverse("index"))
        return render(request, self.template_name, context)

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            login(request, user)
            messages.info(request, "Successfully login")
            return redirect(request.session["referer"])

        return render(request, self.template_name, {"form": form})

def profile(request, username):
    owner = get_object_or_404(User, username=username)
    context = {}
    context['title'] = "User Profile"

    # Get login user
    # * if user_id == user.pk -> print self profile + enrolled courses
    # * not equal -> print open profile
    if request.user != owner:
        context["others_name"] = owner.get_username()
    else:
        context["course_info_list"] = get_enrolled_courses(request.user)
        context["owner"] = owner
        context["owner_aux"] = owner.auxiliary

    return render(request, 'users/profile.html', context)

def logout_func(request):
    logout(request)
    return redirect(request.META['HTTP_REFERER'])

class EditUserInfoView(SetLoginRequiredMixin, View):
    template_name = "users/edit.html"

    def get_context_data(self, *args, **kwargs):
        context = {}
        context["title"] = "Edit User Info"
        return context
    
    def get(self, request):
        # Do authentication elsewhere
        context = self.get_context_data()

        user = request.user
        form = EditForm(initial={'email': user.email, 'realname': user.auxiliary.realname, 'uid': user.auxiliary.uid})
        context["form"] = form

        return render(request, self.template_name, context)

    def post(self, request):
        # Do authentication elsewhere
        context = self.get_context_data()
        form = EditForm(request.POST)

        if form.is_valid():
            user = request.user
            data = form.cleaned_data

            user.email = data['email']
            user.auxiliary.realname = data['realname']
            user.auxiliary.uid = data['uid']

            user.save()
            user.auxiliary.save()
            messages.info(request, "Successfully update")
            return redirect(reverse("users:profile", args=[user.username]))
        context['form'] = form

        return render(request, self.template_name, context)

src/templates/users/edit.html
{% extends 'generics/base.html' %}

{% block content %}

<form action="{% url 'users:edit' %}" method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}

    <div class="row">
        <div class="col-2 text-center">
            <label for="{{ form.email.id_for_label }}">Email:</label>
        </div>
        <div class="col-3">
            {% comment %} {{ form.username}} {% endcomment %}
            <input type="text" id="{{ form.email.id_for_label }}" name="email" class="form-control" value="{{ form.email.value }}" required>
        </div>
        <div class="col-auto text-warning">
            {{ form.email.errors }}
        </div>
    </div>

    <div class="row">
        <div class="col-2 text-center">
            <label for="{{ form.realname.id_for_label }}">Realname:</label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.realname.id_for_label }}" name="realname" class="form-control" value="{{ form.realname.value }}">
        </div>
    </div>

    <div class="row">
        <div class="col-2 text-center">
            <label for="{{ form.uid.id_for_label }}">UID:</label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.uid.id_for_label }}" name="uid" class="form-control" value="{{ form.uid.value }}">
        </div>
    </div>

    <input type="submit" value="Update" 
        class="col-auto offset-md-5">
</form>



{% endblock content %}

src/templates/users/login.html
{% extends "generics/base.html" %}

{% block content %}
<div class="container-fluid">
    {% comment %} <div class="row">
        {% if error %}
            <h1>{{ error }}</h1>
        {% endif %}
    </div> {% endcomment %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% comment %} {{ form }} {% endcomment %}
        {% if form.non_field_errors %}
            <div class="row text-danger">
                <p>Errors occur:</p>
                {{ form.non_field_errors.as_ul }}
            </div>
        {% endif %}

        <div class="row">
            <div class="col-2 text-center">
                <label for="{{ form.username.id_for_label }}">Username:</label>
            </div>
            <div class="col-3">
                {% comment %} {{ form.username}} {% endcomment %}
                <input type="text" id="{{ form.username.id_for_label }}" name="username" class="form-control" required>
            </div>
            <div class="col-auto text-warning">
                {{ form.username.errors }}
            </div>
        </div>

        <div class="row">
            <div class="col-2 text-center">
                <label for="{{ form.password.id_for_label }}">Password:</label>
            </div>
            <div class="col-3">
                {% comment %} {{ form.password }} {% endcomment %}
                <input type="password" id="{{ form.password.id_for_label }}" name="password" class="form-control" aria-describedby="passwordHelpInline" required>
            </div>
            <div class="col-auto text-warning">
                <span id="passwordHelpInline" class="form-text">
                    {{ form.password.errors }}
                </span>
            </div>
        </div>
    <input type="submit" value="Login" 
        class="offset-md-5">
    </form>

    <a href="{% url "users:signup" %}" id="signup">Sign up</a>


</div>

{% endblock content %}

src/templates/users/profile.html
{% extends "generics/base.html" %}

{% block title %}
{{ user.nickname }}
{% endblock title %}

{% block content %}

{% if course_info_list == None %}
    {# Viewing from other users #}
    <p>Hello {{ user.name }}, this is profile of {{ others_name }}</p>
{% else %}
    <p>Welcome {{ owner.username }}!</p>
{% endif %}

{# Here is for open user profile #}
{% if course_info_list %}
<div id="myCourses">
    <h2>My Courses:</h2>

    <div class="list-group w-50">
        {% for course_info in course_info_list %}
            <a href="{% url 'courses:course_homepage' course_info.id %}" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex justify-content-between">
                    <h5 class="mb-1">{{ course_info.name }}</h5>
                </div>
                <p class="mb-1">Course Role:{{ course_info.role }}</p>
            </a>
        {% endfor %}
    </div>

    <h2>My Information:</h2>
    <table>
        <tr>
            <td>Email</td>
            <td>: {{ owner.email | default:"N/A" }}</td>
        </tr>
        <tr>
            <td>UID</td>
            <td>: {{ owner_aux.uid | default:"N/A" }}</td>
        </tr>
    </table>
    <a href="{% url 'users:edit' %}">Edit Information</a>
{% endif %}

{% endblock content %}

src/templates/users/signup.html
{% extends "generics/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static " public/css/main.css" %}">

{% block content %}

  {% if form.non_field_errors %}
  <ul class='form-errors' style="color:Tomato;">
    {% for error in form.non_field_errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  <form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    {% comment %} {{ form.as_table }} {% endcomment %}

    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.username.id_for_label }}" class="col-form-label">
              Username:
            </label>
        </div>
        <div class="col-3">
            {% comment %} {{ form.username}} {% endcomment %}
            <input type="text" id="{{ form.username.id_for_label }}"
               name="username" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.username.errors }}
        </div>
    </div>

    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.email.id_for_label }}" class="col-form-label">
              Email:
            </label>
        </div>
        <div class="col-3">
            {% comment %} {{ form.username}} {% endcomment %}
            <input type="text" id="{{ form.email.id_for_label }}" 
              name="email" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.email.errors }}
        </div>
    </div>

    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.password1.id_for_label }}" class="col-form-label">
              Password:
            </label>
        </div>
        <div class="col-3">
            {% comment %} {{ form.username}} {% endcomment %}
            <input type="text" id="{{ form.password1.id_for_label }}"
              name="password1" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.password1.errors }}
        </div>
    </div>

    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.password2.id_for_label }}" class="col-form-label">
              Password Again:
            </label>
        </div>
        <div class="col-3">
            {% comment %} {{ form.username}} {% endcomment %}
            <input type="text" id="{{ form.password2.id_for_label }}"
               name="password2" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.password2.errors }}
        </div>
    </div>

    <input type="submit" value="Create"
      class="col-auto offset-md-5">
  </form>

{% endblock content %}