src/courses/urls.py
from django.urls import path

from . import views, views_my
import homeworks.views as homework_views

app_name = 'courses'
urlpatterns = [
    # Basic operation
    # path('', views.PlatformHomepageView.as_view(), name='index'),
    path('create', views.CreateCourseView.as_view(), name='course_create'),
    path('<int:course_id>', views.course_homepage, name='course_homepage'),
    path('<int:pk>/edit', views.EditCourseView.as_view(), name='course_edit'),
    path('<int:course_id>/join', views.joinCourse, name='course_join'),

    # My* Views
    path('myTeaching', views_my.MyTeachingCourseListView.as_view(), name='teaching_list_my'),
    path('myStudying', views_my.MyStudyingCourseListView.as_view(), name='studying_list_my'),
    path('myTasks', views_my.MyTasksListView.as_view(), name='tasks_list_my'),

    # Member management
    path('<int:course_id>/students', views.StudentsListView.as_view(), name='students_manage'),
    path('changePrivilege/<int:member_record>', views.ChangePrivilegeView.as_view(), name='privilege_change'),

    # Task handling 
    path('<int:course_id>/tasks', homework_views.TaskListView.as_view(), name='task_list'),
    path('<int:course_id>/createTask', homework_views.CreateTaskView.as_view(), name='task_create'),
    path('task/<int:task_id>', homework_views.TaskDetailView.as_view(), name='task_detail'),
    path('task/<int:pk>/update', homework_views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:task_id>/submissions', homework_views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:pk>/comment', homework_views.SubmissionCommentUpdateView.as_view(), name='submission_comment'),

    # TODOs
    # path('<int:course_id>/announcements', views.manageAnnounce, name='manage_announces'),
]

src/files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    # path('', views.FileCreateView.as_view(), name='index'),
    path('', views.TestUploadFileFormView.as_view(), name='index'),
    path('download/<int:file_id>', views.downloadFile, name='download'),
    path('delete/<int:file_id>', views.deleteFile, name='delete'),
]

src/trial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
import courses.views, users.views

urlpatterns = [
    path('', courses.views.PlatformHomepageView.as_view(), name='index'),
    path('login/', users.views.LoginView.as_view(), name='login'),
    # path('', index, name="home"),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('homeworks/', include('homeworks.urls')),
    path('files/', include('files.urls')),
    path('dockers/', include('dockers.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.LoginView.as_view(), name='index'),
    # path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'logout/', views.logout_func, name='logout'),
    path(r'signup/', views.SignupView.as_view(), name='signup'),
    path(r'profile/<str:username>', views.profile, name='profile'),
    path(r'profile_edit', views.EditUserInfoView.as_view(), name='edit'),
]

src/templates/generics/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="container no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="container no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="container no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="container no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/boostrap.bundle.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>

<div id="header" class="header container-fluid row">
    {# hard coded image, in the `trial/trial/static` #}
    <div class="logo col-sm-2 center">
        <a href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" alt="CAaD" width="" height="50"></a>
    </div>
        <div class="title col-sm-8">
            <h1>{{ title | default:"Fill in title variable" }}<h1>
        </div>
    <div class="user col-sm-2">

        {% block status %}
            {% if user.is_authenticated %}
            Hello 
            <a href="{% url 'users:profile' user.username %}">
            {{ user.username }}
            </a>
            . <a href="{% url 'users:logout' %}">Logout</a>
            {% else %}
            Anonymous User. <a href="{% url 'login' %}">Login</a>
            {% endif %}
        {% endblock status %}

    </div>
</div>


<div id="body" class="container-fluid row">
    <div class="navi col-sm-2 flex-fill">
    <nav class="navbar navbar-default" role="navigation">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-link" href='{% url "index" %}'>Homepage</a>
            </li>
            {% block navigation %}
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href='{% url "courses:studying_list_my" %}'>My Studying</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href='{% url "courses:tasks_list_my" %}'>My Tasks</a>
            </li>

            {% endif %}
            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href='{% url "courses:teaching_list_my" %}'>My Teaching</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href='{% url "admin:index" %}'>Administration</a>
            </li>
            {% endif %}

            {% comment %} <li class="nav-item"><a class="nav-link" href="#">SVN</a></li>
            <li class="nav-item dropdown btn-group">
                <a href="#" class="nav-link dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown">
                    Java
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href="#">jmeter</a></li>
                    <li><a class="dropdown-item" href="#">EJB</a></li>
                    <li><a class="dropdown-item" href="#">Jasper Report</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">分离的链接</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">另一个分离的链接</a></li>
                </ul>
            </li> {% endcomment %}
            {% endblock %}

        </ul>
    </nav>
    </div>

    <div class="content col-sm-10 container">

    <div class="row align-items-baseline text-warning">
    {% block message_framework %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == default_message_levels.error %}important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endblock message_framework %}
    </div>


    <div class="row align-items-center">
        {% block content%}
        <div>
            <p>Here comes the main content</p>
        </div>
        {% endblock %}
    </div>


    <div class="row align-items-end">
    {% block error_display %}
    {% if form %}
        {% comment %} {% if form.errors %}
        
        <ul class="errors">
            {% for k, v in form.errors.items %}

            <li>{{ k }}: {{ v }}</li>
            
            {% endfor %}
        </ul>
        {% endif %} {% endcomment %}

        {% if form.non_field_errors %}
        
        <p>Here are the errors:</p>
        <ol class="non_field_errors bg-danger">
        {% for error in form.non_field_errors %}

        <li>{{ error }}</li>
        
        {% endfor %}
        </ul>
        
        {% endif %}
    {% endif %}
    {% endblock error_display %}
    </div>


    </div>

</div>


<script src="" async defer>
{% block script %}{% endblock script %}
</script>
    </body>
</html>

src/templates/generics/error.html
{% extends 'generics/base.html' %}

{% block content %}

{{ error_msg }}

{% if error_id == 0 %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}

{% if redirect_to != None %}
    <a href="{{ redirect_to }}">Go back.</a>
{% endif %}

{% endblock content %}

src/templates/generics/info.html
{% extends 'generics/base.html' %}

{% block content %}

{{ msg }}

{% if redirect_to %}
<a href="{{ redirect_to }}">Click here to jump.</a>
{% endif %}

{% if previous != None %}
<a href="{{ previous }}">Go back to previous page.</a>
{% endif %}

{% endblock content %}

src/templates/generics/navi.html
{% for navi in navi_list %}
    <li class="nav-item">
        <a class="nav-link" href='{{ navi.url }}'>{{ navi.name }}</a>
    </li>
{% endfor %}