src/courses/urls.py
from django.urls import path

from . import views, views_my
import homeworks.views as homework_views

app_name = 'courses'
urlpatterns = [
    # Basic operation
    # path('', views.PlatformHomepageView.as_view(), name='index'),
    path('create', views.CreateCourseView.as_view(), name='course_create'),
    path('<int:course_id>', views.course_homepage, name='course_homepage'),
    path('<int:pk>/edit', views.EditCourseView.as_view(), name='course_edit'),
    path('<int:course_id>/join', views.joinCourse, name='course_join'),

    # My* Views
    path('myTeaching', views_my.MyTeachingCourseListView.as_view(), name='teaching_list_my'),
    path('myStudying', views_my.MyStudyingCourseListView.as_view(), name='studying_list_my'),
    path('myTasks', views_my.MyTasksListView.as_view(), name='tasks_list_my'),

    # Member management
    path('<int:course_id>/students', views.StudentsListView.as_view(), name='students_manage'),
    path('changePrivilege/<int:member_record>', views.ChangePrivilegeView.as_view(), name='privilege_change'),

    # Task handling 
    path('<int:course_id>/tasks', homework_views.TaskListView.as_view(), name='task_list'),
    path('<int:course_id>/createTask', homework_views.CreateTaskView.as_view(), name='task_create'),
    path('task/<int:task_id>', homework_views.TaskDetailView.as_view(), name='task_detail'),
    path('task/<int:pk>/update', homework_views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:task_id>/submissions', homework_views.SubmissionListView.as_view(), name='submission_list'),
    path('submission/<int:pk>/comment', homework_views.SubmissionCommentUpdateView.as_view(), name='submission_comment'),

    # TODOs
    # path('<int:course_id>/announcements', views.manageAnnounce, name='manage_announces'),
]

src/files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    # path('', views.FileCreateView.as_view(), name='index'),
    path('', views.TestUploadFileFormView.as_view(), name='index'),
    path('download/<int:file_id>', views.downloadFile, name='download'),
    path('delete/<int:file_id>', views.deleteFile, name='delete'),
]

src/trial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index
import courses.views, users.views

urlpatterns = [
    path('', courses.views.PlatformHomepageView.as_view(), name='index'),
    path('login/', users.views.LoginView.as_view(), name='login'),
    # path('', index, name="home"),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('homeworks/', include('homeworks.urls')),
    path('files/', include('files.urls')),
    path('dockers/', include('dockers.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.LoginView.as_view(), name='index'),
    # path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'logout/', views.logout_func, name='logout'),
    path(r'signup/', views.SignupView.as_view(), name='signup'),
    path(r'profile/<str:username>', views.profile, name='profile'),
    path(r'profile_edit', views.EditUserInfoView.as_view(), name='edit'),
]

src/courses/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User, Group
from django.utils.timezone import now
from django.dispatch import receiver
from django.db.models.signals import post_save

root = User.objects.get(username="root")

class Course(models.Model):
    """
    Course in the teaching platform
    """
    name = models.CharField('course name', max_length=32)
    password = models.CharField('joining password', max_length=8)
    description = models.CharField('description', max_length=512)
    is_open = models.BooleanField("Is open to all", default=True)

    create_date = models.DateTimeField('date created up', default=now())

    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Course({}-{})".format(self.name, self.creator.username)

    @classmethod
    def is_password_for_course(cls, course_id, pwd_to_check):
        obj = cls.objects.get(pk=course_id)
        if obj:
            return (obj.password == pwd_to_check)
        return False
    
    @classmethod
    def get_all_teacher_courses(cls, user):
        """
        Get all the id of courses which user is teacher or admin

        Input:
            * self: the user
        Output:
            * list(course_id)
        """
        member_record = CourseMember.objects.filter(user=user)
        member_teacher = member_record.filter(Q(type = 0) | Q(type = 1) | Q(type = 2))
        teacher_list = []

        for member in member_teacher:
            if member.course.pk not in teacher_list:
                teacher_list.append(member.course.pk)

        return teacher_list
    @classmethod
    def get_all_student_courses(cls, user):
        """
        Get all the id of courses which user is student

        Input:
            * self: the user
        Output:
            * list(course_id)
        """
        member_record = CourseMember.objects.filter(user=user)
        member_teacher = member_record.filter(type = 3)
        student_list = []

        for member in member_teacher:
            if member.course.pk not in student_list:
                student_list.append(member.course.pk)

        return student_list



class CourseMember(models.Model):
    """
    Class used to express the relationship between User and Course

    Four types of user in the course: 
        * admin: createor, so do whatever you want
        * teacher: assigned by the admin of the course
        * assistant: only can revise tasks
        * student: least privilege in course
    """
    MEMBER_TYPE = [(0, 'admin'), (1, 'teacher'),
                   (2, 'assistant'), (3, 'student')]

    type = models.IntegerField(
        choices=MEMBER_TYPE, verbose_name='Member type')

    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    @classmethod
    def get_highest_course_privilege(cls, user_id, course_id):
        if user_id == None or course_id == None:
            return 4

        cm = cls.objects.filter(course__pk=course_id).filter(user__pk=user_id)

        if len(cm) > 0:
            # Probably multiple role, pick the highest privilege
            type = 3
            for role in cm:
                if role.type < type:
                    type = role.type
            return type
        return 4

    @classmethod
    def is_teacher_of(cls, user_id, course_id):
        """
        Check user is teacher of course

        Input:
            * user_id: user's id
            * course_id: courses's id
        Output:
            * True/False
        """
        return (cls.get_highest_course_privilege(user_id, course_id) < 2)

    @classmethod
    def is_student_of(cls, user_id, course_id):
        cm = cls.objects.filter(course__pk=course_id).filter(user__pk=user_id)

        for role in cm:
            if role.type == 3:
                return True
        return False

    @classmethod
    def is_member_of(cls, user_id, course_id):
        return (cls.get_highest_course_privilege(user_id, course_id) < 4)
    
    @classmethod
    def join_course_as_student(cls, user_id, course_id):
        course = Course.objects.get(pk=course_id)
        user = User.objects.get(pk=user_id)
        cm = cls(course=course, user=user, type=3)
        cm.save()

    @classmethod
    def update_member_privilege_staff(cls, user_id):
        user = User.objects.get(pk=user_id)
        group = Group.objects.get(name="teacher")
        cms = CourseMember.objects.filter(user__pk=user_id)
        type = 4
        for cm in cms:
            if cm.type < type:
                type = cm.type
        if type > 2:
            user.is_staff = False
            group.user_set.remove(user)
        else:
            user.is_staff = True
            group.user_set.add(user)
        user.save()
        group.save()
    @classmethod
    def get_highest_privilege(cls, user_id):
        cm = cls.objects.filter(user__pk=user_id).only("type").distinct()
        privilege = 4
        for p in cm:
            if p < privilege:
                privilege = p
        return p

@receiver(post_save, sender=CourseMember)
def update_member_privilege_staff(sender, **kwargs):
    print("Receive signal from {}".format(sender))
    instance = kwargs.pop("instance")
    created = kwargs.pop("created")
    update_fields = kwargs.pop("update_fields")

    if not created:
        if update_fields is not None and "type" not in update_fields:
            return False
    CourseMember.update_member_privilege_staff(instance.user.pk)

    return True

src/courses/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponse
from django.views.generic import View, ListView, DetailView, UpdateView
from django.views.generic.base import ContextMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.mixins import UserPassesTestMixin

from users.models import User
from utils.general import error_not_authenticated, return_error, info
from courses.utils import *

from utils.check import SetLoginRequiredMixin, CheckGreaterPrivilegeMixin
from utils.params import *
from .models import Course, CourseMember
from .forms import CreateCourseForm, JoinForm
from .utils import getRandCPwd
# from .signals import update_user_privilege_signal

class PlatformHomepageView(ListView):
    queryset = Course.objects.order_by('name').filter(is_open=True).all()
    paginate_by = 3
    context_object_name = "course_list"
    template_name = "courses/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Homepage"
        return context
    

class CreateCourseView(SetLoginRequiredMixin, View, ContextMixin):
    template_name = 'courses/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Course"
        return context

    def get(self, request):
        # if not request.user.is_authenticated:
        #     return error_not_authenticated(request)
        context = self.get_context_data()
        form = CreateCourseForm(creator=request.user)
        context['form'] = form

        return render(request, self.template_name, context)

    def post(self, request):
        # if not request.user.is_authenticated:
        #     error_not_authenticated(request)

        # Create a course for him
        user = request.user
        form = CreateCourseForm(request.POST, creator=user)
        if form.is_valid():
            # Save creator
            obj = form.save()
            obj.creator = user
            obj.save()
            # Add role in CourseMember
            cm = CourseMember(
                course = obj, 
                user = user,
                type = COURSEMEMBER_ADMIN
            )
            cm.save()
            # Set user as staff
            user.is_staff = True
            user.save()

            return info(request, "Successfully create course", redirect_to=reverse("courses:course_homepage", args=[obj.pk]))
        return return_error(request, FORM_NOT_VALID)


def course_homepage(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user
    context = {}
    context['title'] = "Course Homepage"

    # Two stages
    # 1. Open to everyone or member -> basic info
    # 2. Is teacher -> to member management
    # Stage 1
    privilege = CourseMember.get_highest_course_privilege(user.pk, course.pk)
    if course.is_open or privilege != 4:
        context['course'] = course

        if privilege == 4:
            context['role'] = "Visitor"
            form = JoinForm(initial={"id": course_id})
            context['join_form'] = form
        else:
            context['role'] = COURSEMEMBER_TYPE[privilege]
            context['is_member'] = True
    
    # Stage 2
    if CourseMember.is_teacher_of(user.pk, course_id):
        context['is_teacher'] = True
    
    return render(request, "courses/homepage.html", context=context)


class EditCourseView(CheckGreaterPrivilegeMixin, UpdateView):
    least_privilege = COURSEMEMBER_ADMIN

    model = Course
    fields = ['name', 'password', 'description', 'is_open']
    template_name = "courses/update.html"

    def dispatch(self, request, *args, **kwargs):
        self.course_id = kwargs["pk"]
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] =  "Edit Course"
        return context

    def form_valid(self, form):
        clean = form.cleaned_data
        if clean['password'] == '':
            self.object.password = getRandCPwd()
            self.object.save()
        self.success_url = reverse("courses:course_homepage", args=[self.object.pk])
        return super().form_valid(form)


@login_required
def joinCourse(request, course_id):
    if request.method != "POST":
        return info(request, "Wrong HTTP method for {}. POST only".format(request.path),
                redirect_to=reverse("courses:course_homepage", args=[course_id]))

    # Check password and join class
    form = JoinForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        if Course.is_password_for_course(course_id, data['password']):
            CourseMember.join_course_as_student(request.user.pk, course_id)
            return info(request, "Successfully join as student.", reverse("courses:course_homepage", args=[course_id]))
    return return_error(request, FORM_NOT_VALID)


class StudentsListView(CheckGreaterPrivilegeMixin, ListView):
    paginate_by = 10
    template_name = 'courses/students.html'
    context_object_name = 'student_list'
    least_privilege = COURSEMEMBER_TEACHER

    def dispatch(self, request, *args, **kwargs):
        self.course_id = kwargs["course_id"]
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        course_id = self.kwargs['course_id']
        privilege = CourseMember.get_highest_course_privilege(user.pk, course_id)
        return CourseMember.objects.filter(course__id=course_id, type__gt=privilege)

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        context['title'] = "Student List"
        context['course_id'] = self.kwargs['course_id']
        return context

    def get(self, request, course_id):
        if not request.user.is_authenticated:
            return error_not_authenticated(request)

        # Authorized user
        # self.object_list = self.object_list.filter(type__lt=CourseMember.get_course_privilege(request.user.pk, course_id))
        return super(StudentsListView, self).get(self, request)


class ChangePrivilegeView(SetLoginRequiredMixin, ContextMixin, View):
    template_name = "courses/student_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Change Member Privilege"
        return context

    def get(self, request, member_record):
        course = get_object_or_404(CourseMember, pk=member_record).course
        if not CourseMember.is_teacher_of(request.user.pk, course.pk):
            return return_error(USER_NOT_AUTHORIZED)

        cm = get_object_or_404(CourseMember, pk=member_record)
        context = self.get_context_data()
        context['cm'] = cm
        context['type_readable'] = COURSEMEMBER_TYPE[cm.type]
        context['course_id'] = course.pk
        context['member_record'] = member_record 
        context['privilege'] = CourseMember.get_highest_course_privilege(request.user.pk, course.pk)
        return render(request, self.template_name, context)

    def post(self, request, member_record):
        course = get_object_or_404(CourseMember, pk=member_record).course
        if CourseMember.is_teacher_of(request.user.pk, course.pk):
            cm = get_object_or_404(CourseMember, pk=member_record)

            if cm.user.pk != int(request.POST['user_id']):
                # return render(request, "courses/info.html", {"info": "Conflicting record and user."})
                return info(request, "Conflicting record and user")

            update_fields = []
            if cm.type != request.POST['privilege']:
                cm.type = request.POST['privilege']
                update_fields.append("type")

            cm.save()
            return redirect(reverse("courses:students_manage", args=[course.pk]))
        return return_error(USER_NOT_AUTHORIZED)

src/templates/courses/create.html
{% extends "generics/base.html" %}

{% block content %}

<form action="{% url "courses:course_create" %}" method="POST">
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
    {% csrf_token %}
    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.name.id_for_label }}" class="col-form-label">
              Course Name:
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.name.id_for_label }}"
               name="name" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.name.errors }}
        </div>
    </div>
    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.password.id_for_label }}" class="col-form-label">
              Password:
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.password.id_for_label }}"
               name="password" class="form-control">
        </div>
        <div class="col-auto text-warning">
            {{ form.password.errors }}
        </div>
    </div>
    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.description.id_for_label }}" class="col-form-label">
              Description:
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.description.id_for_label }}"
               name="description" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.description.errors }}
        </div>
    </div>
    <input type="submit" value="Create" 
        class="col-auto offset-md-5">
</form>

{% endblock content %}

src/templates/courses/homepage.html
{% extends "generics/base.html" %}

{% block content %}

{% if course %}
    <h2>Welcome, {{ user.username }} as {{ role }}</h2>
    {# Basic information #}
    <div class="container-fluid">
        <div class="basic_info">
            <div class="row">
                <h5>Course ID: {{ course.pk }}</h5>
                <h5>Course name:{{ course.name }}</h5>
                <h5>Creator:{{ course.creator.username }}</h5>
                <h5>Descrition:{{ course.description }}</h5>
            </div>
        </div>
    </div>

    <div class="extend container-fluid">
    {% if is_teacher %}
        <div class="row">
            <p>Course password: {{ course.password }}</p>
            <p>
            Open course?: 
                {% if course.is_open %}
                Yes
                {% else %}
                No. Student can only join with Course ID and course password.
                {% endif %}
            </p>
        </div>

        <div class="row">
            <a href="{% url 'courses:course_edit' course.pk %}" class="btn btn-primary col-3 text-center" style="height: max-content;">
                Edit Info 
            </a>
            <br>
            <a href="{% url 'courses:students_manage' course.pk %}" class="btn btn-primary col-3" style="height: max-content;">
                Student List
            </a>
            <br>
            {% comment %} <a href="{% url 'courses:task_list' course.pk %}" class="btn btn-primary col-3" style="height: max-content;">
                Review Submissions
            </a> {% endcomment %}
        </div>
    {% endif %}

    {% if is_member %}
    <div class="row mt-3">
        <a href="{% url 'courses:task_list' course.pk %}" class="btn btn-primary col-3">Task list</a>
    </div>
    {% else %}
    <h2>Join Course NOW</h2>
        {% include "courses/includes/join_form.html" %}
    {% endif %}

{% else %}
    <h2>This course is not OPEN for public access.</h2>
    <p>Please contact the course administrator.</p>
{% endif %}
{% endblock content %}

src/templates/courses/index.html
{% extends 'generics/base.html' %}

{% block content %}

<div class="list_courses m-3">
    <div class="container-fluid row">
        <h2 class="col-7">Available courses list:</h2>
        <div class="create_course col-5 d-flex justify-content-end align-items-end ">
            <a href="{% url "courses:course_create" %}" class="btn btn-primary text-wrap">
                Create New course
            </a>
        </div>
    </div>
    <div class="row">
        {% if course_list %}
            <div class="d-flex justify-content-center mt-3">
                {% for course in course_list %}
                <div class="card col-3 m-1">
                <div class="card-body">
                    <h5 class="card-title">{{ course.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">By {{ course.creator.username }}</h6>
                    <p class="card-text" style="height: 5rem;">{{ course.description }}</p>
                    <a href="{% url 'courses:course_homepage' course.pk %}" class="btn btn-primary">Go!</a>
                </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
        <h3 class="d-flex justify-content-evenly mt-5">No courses are available for {{ title }}</h3>
        {% endif %}
    </div>

    {% if page_obj %}
    <nav aria-label="Page navigation example">
    <ul class="pagination d-flex justify-content-center m-3">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item"><a class="page-link disabled" href="#" disabled>Previous</a></li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item"><a class="page-link disabled" href="#" disabled>Next</a></li>
        {% endif %}
    </ul>
    </nav>
    {% endif %}
</div>

{% endblock content %}

src/templates/courses/student_detail.html
{% extends "generics/base.html" %}

{% block content %}

<div class="container-fluid">
<form action="{% url 'courses:privilege_change' member_record %}" method='post'>
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
    {% csrf_token %}

    <div class="row">
        <label for="username" class="col-4">Member Username</label>
        <p id="username" class="col-3">{{ cm.user.username }}</p>
    </div>
    <div class="row">
        <label for="username" class="col-4">Member Privilege</label>
        <p id="username" class="col-3">{{ type_readable }}</p>
    </div>
    <div class="row">
        <input type="text" name="user_id" value="{{ cm.user.pk }}" hidden>
        {% if privilege == 0 %}

            <label for="privilege" class="col-4">Choose a new privilege:</label>
            <select name="privilege" id="privilege_select" class="col-3" style="height: 100%" required>
                <option value="" selected disabled hidden>Choose Privilege</option>
                <option value="1">Teacher</option>
                <option value="2">Assistant</option>
                <option value="3">Student</option>
            </select> 

        {% else %}
        {# Privilege == 1 #}

            <select name="privilege" id="privilege_select" required>
            <option value="" selected disabled hidden>Choose Privilege</option>
            <option value="2">Assistant</option>
            <option value="3">Student</option>
            </select> 

        {% endif %}
    </div>
    <div class="row">
        <div class="d-flex justify-content-center mt-3">
            <input type="submit" value="Submit new Privilege" style="width: 16rem;">
        </div>
    </div>


</form>

</div>
{% endblock content %}

src/templates/courses/students.html
{% extends 'generics/base.html' %}

{% block content %}

<div class="container mt-2">
<table class="table">
<thead>
    <tr>
    <th scope="col" hidden="True">id</th>
    <th scope="col">User</th>
    <th scope="col">Type</th>
    <th scope="col">Change</th>
    </tr>
</thead>

{% for member_record in student_list %}
    <tr>
        <td hidden="True">{{ member_record.pk }}</td>
        <td>
            <a href="{% url 'users:profile' member_record.user.username %}">
                {{ member_record.user }}
            </a>
        </td>
        <td>
            {% if member_record.type == 1 %}
            Teacher
            {% elif member_record.type == 2 %}
            Assistant
            {% elif member_record.type == 3 %}
            Student
            {% endif %} 
        </td>
        <td><a href="{% url 'courses:privilege_change' member_record.pk %}">Change privilege</a></td>
    </tr>
{% endfor %}
</table>
</div>

{% if page_obj %}
<nav aria-label="Page navigation example">
<ul class="pagination d-flex justify-content-center m-3">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Previous</a></li>
    {% endif %}
    {% for object in page_obj.paginator.page_range %}
        <li class="page-item">
            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Next</a></li>
    {% endif %}
</ul>
</nav>
{% endif %}

{% endblock content %}

src/templates/courses/tasks.html
{% extends 'generics/base.html' %}

{% block content %}

<div class="container mt-2">
<table class="table">
<thead>
    <tr>
    <th scope="col">Course</th>
    <th scope="col">Task</th>
    <th scope="col">Status</th>
    <th scope="col">Link</th>
    </tr>
</thead>

{% for task in task_list %}
    <tr>
        <td>
            {{ task.course.name }}
        </td>
        <td>
            {{ task.title }}
        </td>
        <td>
            {% if task.status == 0 %}
            Draft
            {% elif task.status == 1 %}
            Running
            {% else %}
            Closed
            {% endif %}
        </td>
        <td>
            <a href="{% url 'courses:task_detail' task.pk %}">
                Go!
            </a>
        </td>
    </tr>
{% endfor %}
</table>
</div>

{% if page_obj %}
<nav aria-label="Page navigation example">
<ul class="pagination d-flex justify-content-center m-3">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Previous</a></li>
    {% endif %}
    {% for object in page_obj.paginator.page_range %}
        <li class="page-item">
            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item"><a class="page-link disabled" href="#" disabled>Next</a></li>
    {% endif %}
</ul>
</nav>
{% endif %}

{% endblock content %}

src/templates/courses/update.html
{% extends 'generics/base.html' %}

{% block content %}

<form method="post">
    {% if form.non_field_errors %}
        <div class="row text-danger">
            <p>Errors occur:</p>
            {{ form.non_field_errors.as_ul }}
        </div>
    {% endif %}
    {% csrf_token %}

    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.name.id_for_label }}" class="col-form-label">
              Course Name:
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.name.id_for_label }}"
               name="name" class="form-control" value="{{ form.name.value }}" required>
        </div>
        <div class="col-auto text-warning">
            {{ form.name.errors }}
        </div>
    </div>
    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.password.id_for_label }}" class="col-form-label">
                Joining Password
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.password.id_for_label }}"
               name="password" value="{{ form.password.value }}" class="form-control">
        </div>
        <div class="col-auto text-warning">
            {{ form.password.errors }}
        </div>
    </div>
    <div class="row m-3">
        <div class="col-3 text-center">
            <label for="{{ form.description.id_for_label }}" class="col-form-label">
                Description
            </label>
        </div>
        <div class="col-3">
            <input type="text" id="{{ form.description.id_for_label }}"
               name="description" value="{{ form.description.value }}" class="form-control"  required>
        </div>
        <div class="col-auto text-warning">
            {{ form.description.errors }}
        </div>
    </div>

    <div class="form-check offset-3">
    <label class="form-check-label col-3" for="{{ form.is_open.id_for_label }}">
        Open Course
    </label>
    <input class="form-check-input" type="checkbox" value="" id="{{ form.is_open.id_for_label }}">
    </div>

    <input type="submit" value="Submit!" 
        class="col-auto offset-md-5">
</form>

{% endblock content %}